[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "backend"
version = "1.0.0"
description = "Flask Backend for Monorepo"
readme = "README.md"
authors = [
    { name = "Developer", email = "developer@example.com" }
]
requires-python = ">=3.11"
dependencies = [
    "Flask>=3.0.0",
    "Flask-Cors>=4.0.0"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 88
target-version = ['py311']

[tool.ruff]
line-length = 88
target-version = "py311"
